class ACHIEVEMENT_CHOICES:
    SUM_MEASUREMENTS_COMPLETED = "SUM_MEASUREMENTS_COMPLETED"
    SUM_TRAININGS_COMPLETED = "SUM_TRAININGS_COMPLETED"
    SUM_LOGGED_TIME = "SUM_LOGGED_TIME"
    LOGGED_TIME = "LOGGED_TIME"
    SUM_USER_MODIFY_TRAINING = "SUM_USER_MODIFY_TRAINING"