
services:
  trueeffects_nginx:
    image: saxatachi/trueeffects_nginx:dev
    container_name: trueeffects_nginx
    build:
      context: .
      dockerfile: ./compose/azure-dev/nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - backend
    restart: always
    volumes:
      - /app/backend/local-backend-static:/app/backend/local-backend-static
    depends_on:
      - trueeffects_backend


  trueeffects_backend:
    image: saxatachi/trueeffects_backend:dev
    container_name: django
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 & celery -A backend.tasks worker --loglevel=info"
    volumes:
      - /app/backend/local-backend-static:/app/backend/local-backend-static
      - .:/app
    env_file:
      - ./.envs/azure_dev/.django
    networks:
      - backend
#    depends_on:
#      - trueeffects_db

networks:
  backend:

volumes:
  postgres_data: