version: "3.7"
services:
  trueeffects_nginx:
    image: nginx
    container_name: trueeffects_nginx
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    ports:
      - "81:81"
      - "444:444"
    networks:
      - backend
    restart: always
    volumes:
      - "/app/backend/local-backend-static:/app/backend/local-backend-static"
    depends_on:
      - trueeffects_backend
      - trueeffects_frontend

  trueeffects_db:
    container_name: trueeffects_db
    image: postgres
    environment:
      - POSTGRES_DB=postgres5
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5433
    networks:
      - backend
    ports:
      - "5433:5433"

  trueeffects_backend:
    container_name: trueeffects_backend
    build:
      context: .
      dockerfile: ./compose/local/trueeffects_backend/Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001 & celery -A backend.tasks worker --loglevel=info"
#    entrypoint: /app/entrypoint.sh
    volumes:
      - "/app/backend/local-backend-static:/app/backend/local-backend-static"
      - ".:/app"
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.local
      - AUTH_USER_MODEL=authorization.CustomUser
      - REDIS_CONTAINER=trueeffects_redis
      - REDIS_URL=redis://trueeffects_redis:6380/0
    networks:
      - backend
    depends_on:
      - trueeffects_db

  trueeffects_frontend:
    stdin_open: true
    container_name: trueeffects_frontend
    build:
      context: .
      dockerfile: ./compose/local/trueeffects_frontend/Dockerfile
    volumes:
      - "./trueeffectsfrontend:/frontend"
    ports:
      - "3001:3001"
    depends_on:
      - trueeffects_db
      - trueeffects_backend
    networks:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3001

  trueeffects_redis:
    container_name: trueeffects_redis
    image: 'redis:latest'
    ports:
      - '6380:6380'
    command: --port 6380
    networks:
      - backend

networks:
  backend: