#version: "3.7"
services:
  trueeffects_nginx:
    image: nginx
    container_name: trueeffects_nginx
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - backend
    restart: always
    volumes:
      - /app/backend/local-backend-static:/app/backend/local-backend-static
    depends_on:
      - trueeffects_backend
      - trueeffects_frontend

  trueeffects_db:
    container_name: trueeffects_db
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: postgres
    env_file:
      - ./.envs/local/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - backend
#    ports:
#      - 5432:5432

  trueeffects_backend:
    container_name: django
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 & celery -A backend.tasks worker --loglevel=info"
    volumes:
      - /app/backend/local-backend-static:/app/backend/local-backend-static
      - .:/app
#    ports:
#      - 8000:8000
    env_file:
      - ./.envs/local/.django
    networks:
      - backend
    depends_on:
      - trueeffects_db

  trueeffects_frontend:
    stdin_open: true
    container_name: react
    build:
      context: .
      dockerfile: compose/local/react/Dockerfile
    env_file:
      - .envs/local/.react
    volumes:
      - ./trueeffectsfrontend:/frontend
#    ports:
#      - 3000:3000
    depends_on:
      - trueeffects_db
      - trueeffects_backend
    networks:
      - backend

  trueeffects_redis:
    container_name: trueeffects_redis
    build:
      context: .
      dockerfile: ./compose/local/redis/Dockerfile
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data: