services:
  production_trueeffects_db:
    container_name: production_trueeffects_db
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    env_file:
      - .envs/production/.postgres
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
      - ./prod_backups:/prod_backups
    networks:
      - prod_backend

  production_trueeffects_nginx:
    image: nginx
    container_name: production_trueeffects_nginx
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes:
      - /app/backend/production-static:/app/backend/production-static
      - ./trueeffectsfrontend/build:/build
    networks:
      - prod_backend
    ports:
      - 80:80
    restart: always
    depends_on:
      - production_trueeffects_backend

  production_trueeffects_backend:
    container_name: production_trueeffects_backend
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    entrypoint: /app/entrypoint.sh
    volumes:
      - /app/backend/production-static:/app/backend/production-static
    env_file:
      - .envs/production/.django
    depends_on:
      - production_trueeffects_db
    networks:
      - prod_backend

  production_trueeffects_redis:
    container_name: production_trueeffects_redis
    build:
      context: .
      dockerfile: ./compose/production/redis/Dockerfile
    networks:
      - prod_backend

networks:
  prod_backend:

volumes:
  prod_postgres_data: