version: "3.7"
services:
  production_trueeffects_nginx:
    image: nginx
    container_name: production_trueeffects_nginx
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes:
      - "/app/backend/production-static:/app/backend/production-static"
      - "./trueeffectsfrontend/build:/build"
    networks:
      - prod_backend
    ports:
      - "82:82"
      - "445:445"
    depends_on:
      - production_trueeffects_backend

  production_trueeffects_db:
    container_name: production_trueeffects_db
    image: postgres
    env_file:
      - .env_production
    environment:
      - PGPORT=5434
    ports:
      - "5434:5434"
    networks:
      - prod_backend

  production_trueeffects_backend:
    container_name: production_trueeffects_backend
    build:
      context: .
      dockerfile: ./compose/production/trueeffects_backend/Dockerfile
    entrypoint: /app/entrypoint.sh
    volumes:
      - "/app/backend/production-static:/app/backend/production-static"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.production
      - AUTH_USER_MODEL=authorization.CustomUser
      - REDIS_CONTAINER=production_trueeffects_redis
      - REDIS_URL=redis://trueeffects_redis:6381/0
    ports:
      - "8002:8000"
    depends_on:
      - production_trueeffects_db
    networks:
      - prod_backend

  production_trueeffects_redis:
    container_name: production_trueeffects_redis
    image: 'redis:latest'
    ports:
      - '6381:6381'
    networks:
      - prod_backend
    command: --port 6381


networks:
  prod_backend: