services:
  production_trueeffects_nginx:
    image: nginx
    container_name: production_trueeffects_nginx
    build:
      context: .
      dockerfile: ./compose/production-multiple-apps/nginx/Dockerfile
    volumes:
      - "/app/backend/production-static:/app/backend/production-static"
      - "./trueeffectsfrontend/build:/build"
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - prod_backend
      - connector
    restart: always
    depends_on:
      - production_trueeffects_backend

  production_trueeffects_db:
    container_name: production_trueeffects_db
    image: postgres
    env_file:
      - .env_production
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
      - ./prod_backups:/prod_backups
    environment:
      - PGPORT=5434
    networks:
      - prod_backend

  production_trueeffects_backend:
    container_name: production_trueeffects_backend
    build:
      context: .
      dockerfile: ./compose/production/trueeffects_backend/Dockerfile
    entrypoint: /app/entrypoint.sh
    volumes:
      - "/app/backend/production-static:/app/backend/production-static"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.production
      - AUTH_USER_MODEL=authorization.CustomUser
      - REDIS_CONTAINER=production_trueeffects_redis
      - REDIS_URL=redis://trueeffects_redis:6381/0
    depends_on:
      - production_trueeffects_db
    networks:
      - prod_backend
      - connector

  production_trueeffects_redis:
    container_name: production_trueeffects_redis
    image: 'redis:latest'
    networks:
      - prod_backend
    command: --port 6381

#TODO ONLY FOR IPV4
  production_certbot:
    image: certbot/certbot
    container_name: production_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email michal.lejwoda@gmail.com -d true-effects.pl --agree-tos
    networks:
      - prod_backend

networks:
  prod_backend:
  connector:
    external: true
volumes:
  prod_postgres_data: