# Generated by Django 5.2.4 on 2025-08-17 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='achievements/image/')),
                ('minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SumLoggedInTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_earned', models.BooleanField(default=False)),
                ('date_earned', models.DateTimeField(default=datetime.datetime(2025, 8, 17, 10, 45, 23, 864818, tzinfo=datetime.timezone.utc), null=True)),
                ('is_displayed_for_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserModifyTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
            ],
        ),
    ]
