# Generated by Django 5.2.4 on 2025-08-20 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeachievement',
            name='name',
            field=models.CharField(choices=[('SUM_MEASUREMENTS_COMPLETED', 'Sum Measurements Completed'), ('SUM_EXERCISE_CREATED', 'Sum Exercise Created'), ('SUM_TRAININGS_CREATED', 'Sum Trainings Created'), ('SUM_TRAININGS_COMPLETED', 'Sum Trainings Completed'), ('SUM_LOGGED_TIME', 'Sum Logged Time'), ('LOGGED_TIME', 'Logged Time'), ('SUM_USER_MODIFY_TRAINING', 'Sum User Modify Training')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='date_earned',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 10, 16, 14, 684940, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
