# Generated by Django 5.2.4 on 2025-08-20 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_typeachievement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='date_earned',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 15, 42, 14, 430185, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
