# Generated by Django 3.1.7 on 2021-03-19 08:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210219_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleseries',
            name='reps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
