services:
  terraform:
    image: hashicorp/terraform:1.12.2
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      ARM_CLIENT_ID: "${ARM_CLIENT_ID}"
      ARM_CLIENT_SECRET: "${ARM_CLIENT_SECRET}"
      ARM_SUBSCRIPTION_ID: "${ARM_SUBSCRIPTION_ID}"
      ARM_TENANT_ID: "${ARM_TENANT_ID}"
      TF_VAR_ARM_CLIENT_SECRET: "${ARM_CLIENT_SECRET}"
      TF_VAR_ARM_CLIENT_ID: "${ARM_CLIENT_ID}"
      TF_VAR_ARM_SUBSCRIPTION_ID: "${ARM_SUBSCRIPTION_ID}"
      TF_VAR_ARM_TENANT_ID: "${ARM_TENANT_ID}"
      TF_VAR_db_password: "${TF_VAR_db_password}"
      TF_VAR_django_secret_key: "${TF_VAR_django_secret_key}"
      TF_VAR_acr_proxy_image: "${TF_VAR_acr_proxy_image}"
      TF_VAR_acr_app_image: "${TF_VAR_acr_app_image}"
#      TF_WORKSPACE: "staging"
