services:
  terraform:
    image: hashicorp/terraform:1.12.2
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    env_file:
      - ./../../../../.envs/azure_dev/.terraform