# Generated by Django 5.2.4 on 2025-08-17 10:45

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public', models.BooleanField(default=False)),
                ('popularity', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingleSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_weight', models.FloatField(default=0)),
                ('rest', models.IntegerField(default=10)),
                ('concentric_phase', models.IntegerField(default=0)),
                ('eccentric_phase', models.IntegerField(default=0)),
                ('pause_after_concentric_phase', models.IntegerField(default=0)),
                ('pause_after_eccentric_phase', models.IntegerField(default=0)),
                ('reps', models.IntegerField()),
                ('series_num', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.exercise')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Single Series',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MultiSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_num', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.exercise')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('single_series', models.ManyToManyField(to='training.singleseries')),
            ],
            options={
                'verbose_name_plural': 'Multi Series',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.TimeField(default='00:00:00', null=True)),
                ('multi_series', models.ManyToManyField(blank=True, to='training.multiseries')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('growth', models.FloatField(blank=True, null=True)),
                ('left_biceps', models.FloatField(blank=True, null=True)),
                ('right_biceps', models.FloatField(blank=True, null=True)),
                ('left_forearm', models.FloatField(blank=True, null=True)),
                ('right_forearm', models.FloatField(blank=True, null=True)),
                ('left_leg', models.FloatField(blank=True, null=True)),
                ('right_leg', models.FloatField(blank=True, null=True)),
                ('bodyfat', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDimensionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.BooleanField(default=True)),
                ('growth', models.BooleanField(default=False)),
                ('left_biceps', models.BooleanField(default=True)),
                ('right_biceps', models.BooleanField(default=True)),
                ('left_forearm', models.BooleanField(default=True)),
                ('right_forearm', models.BooleanField(default=True)),
                ('left_leg', models.BooleanField(default=True)),
                ('right_leg', models.BooleanField(default=True)),
                ('bodyfat', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('goal', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('finish_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
