# Generated by Django 3.2.23 on 2023-12-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_remove_multiseries_series_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='single_series',
        ),
        migrations.AddField(
            model_name='training',
            name='multi_series',
            field=models.ManyToManyField(to='training.MultiSeries'),
        ),
    ]
