# Generated by Django 3.2.23 on 2023-12-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20231228_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiseries',
            name='series_num',
            field=models.IntegerField(default=0),
        ),
    ]
