# Generated by Django 3.2.23 on 2023-12-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_multiseries_series_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
