# Generated by Django 3.2.23 on 2023-12-28 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0009_alter_training_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('weight', models.FloatField(default=0)),
                ('growth', models.FloatField(default=0)),
                ('left_biceps', models.FloatField(default=0)),
                ('right_biceps', models.FloatField(default=0)),
                ('left_forearm', models.FloatField(default=0)),
                ('right_forearm', models.FloatField(default=0)),
                ('left_leg', models.FloatField(default=0, null=True)),
                ('right_leg', models.FloatField(null=True)),
                ('bodyfat', models.FloatField(null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
