# Generated by Django 3.2.23 on 2023-12-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_auto_20231228_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiseries',
            options={'verbose_name_plural': 'Multi Series'},
        ),
        migrations.AlterModelOptions(
            name='singleseries',
            options={'verbose_name_plural': 'Single Series'},
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='bodyfat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='right_leg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
