# Generated by Django 3.2.23 on 2023-12-28 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0012_auto_20231228_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdimension',
            name='growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='left_biceps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='left_forearm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='left_leg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='right_biceps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='right_forearm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserDimensionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.BooleanField(default=True)),
                ('growth', models.BooleanField(default=False)),
                ('left_biceps', models.BooleanField(default=True)),
                ('right_biceps', models.BooleanField(default=True)),
                ('left_forearm', models.BooleanField(default=True)),
                ('right_forearm', models.BooleanField(default=True)),
                ('left_leg', models.BooleanField(default=True)),
                ('right_leg', models.BooleanField(default=True)),
                ('bodyfat', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
