# Generated by Django 3.2.23 on 2023-12-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_auto_20231228_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
