# Generated by Django 3.2.23 on 2023-12-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_usergoal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='date',
            field=models.DateField(),
        ),
    ]
