# Generated by Django 3.2.23 on 2023-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_alter_usergoal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdimension',
            name='date',
            field=models.DateField(),
        ),
    ]
