# Generated by Django 3.2.23 on 2023-12-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20231228_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='multi_series',
            field=models.ManyToManyField(blank=True, to='training.MultiSeries'),
        ),
    ]
