# Generated by Django 3.2.23 on 2024-01-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_alter_training_multi_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
