# Generated by Django 3.2.23 on 2024-01-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_alter_usergoal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleseries',
            name='series_num',
            field=models.IntegerField(default=0),
        ),
    ]
