# Generated by Django 3.2.23 on 2024-01-18 15:32

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_alter_training_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdimension',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='usergoal',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='userdimension',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdimension',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergoal',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
