# Generated by Django 3.2.23 on 2024-02-07 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_remove_usergoal_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiseries',
            options={'ordering': ['id'], 'verbose_name_plural': 'Multi Series'},
        ),
        migrations.AlterModelOptions(
            name='singleseries',
            options={'ordering': ['id'], 'verbose_name_plural': 'Single Series'},
        ),
    ]
